// Success Messages.
export const SUCCESS_CHILD_ADDED = "CHILD_ADDED";
export const SUCCESS_SPOUSE_ADDED = "SPOUSE_ADDED";

// Error Messages.
export const ERROR_PERSON_NOT_FOUND = "PERSON_NOT_FOUND";
export const ERROR_CHILD_ADDITION_FAILED = "CHILD_ADDITION_FAILED";
export const ERROR_SPOUSE_ALREADY_ASSIGNED = "SPOUSE_ALREADY_ASSIGNED";
export const ERROR_NONE = "NONE";